# find more documentation at: https://codecov.io/gh/ParaToolsInc/taucmdr/settings/yaml
# Validate this file with: `curl --data-binary @codecov.yml https://codecov.io/validate`

codecov:
  branch: unstable
  require_ci_to_pass: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  branches: [master, unstable]


coverage:

  precision: 2
  round: nearest
  status:

    project:
      default:
        branches:
          - '!gh-pages'
        target: auto
        threshold: 0.5

    patch:
      default: on
      target: auto
      threshold: 2

#    changes: false
