# find more documentation at: https://codecov.io/gh/ParaToolsInc/taucmdr/settings/yaml
# Validate this file with: `curl --data-binary @codecov.yml https://codecov.io/validate`
comment:
  layout: "reach, diff, flags, files, changes, sunburst, uncovered"
  behavior: default
#  require_changes: false  # if true: only post the comment if coverage changes
#  require_base: no        # [yes :: must have a base report to post]
#  require_head: yes       # [yes :: must have a head report to post]
coverage:
  status:
    patch: false
    changes: false
    project:
      default:
        branches:
          - '!gh-pages'
        target: auto
        threshold: 0.5
# Codecov is incorrectly detecting low coverage for these files because
# it is not considering both runs of the tests
ignore:
    - packages/taucmdr/cf/storage/sqlite3*
