/**
* Project.js
*
* @description :: TODO: You might write a short summary of how this model works and what it represents here.
* @docs        :: http://sailsjs.org/#!documentation/models
*/

module.exports = {

  schema: true,
  
  attributes: {

    // One-to-many association
    user: {
      model: 'User',
      required: true 
    },

    // Project name
    name: {
      type: 'string',
      required: true
    },

    // Targets used by this project (N-N)
    targets: {
      collection: 'Target',
      via: 'projects',
      dominant: true
    },

    // Applications used by this project (N-N)
    applications: {
      collection: 'Application',
      via: 'projects',
      dominant: true
    },

    // Measurements used by this project (N-N)
    measurements: {
      collection: 'Measurement',
      via: 'projects',
      dominant: true
    },

    // Debuggers used by this project (N-N)
    debuggers: {
      collection: 'Debugger',
      via: 'projects',
      dominant: true
    },

    // Trials generated by this project (1-N)
    trials: {
      collection: 'Trial',
      via: 'project',
      dominant: true
    }

  }
};